version: '2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    container_name: elasticsearch
    environment: 
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    volumes:
      - ${PWD}/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - 9200:9200
      - 9300:9300
    networks: 
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:6.4.2
    container_name: logstash
    volumes:
      - ${PWD}/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ${PWD}/logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - 5000:5000
      - 9600:9600
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.2
    container_name: kibana
    volumes:
      - ${PWD}/kibana/:/usr/share/kibana/config:ro
    ports:
      - 5601:5601
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge
